spring.application.name=relieftrack-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/relieftrack
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.security=INFO

# Custom JWT Config
jwt.secret=9a67471ec6391443d4ec775ab9e3fcf7f22f2813c9e6aa80753068d87b3d30b9
jwt.expiration=86400000
